### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by SergioGasquez**

### CODE REVIEW

**Comment by urish** [comment]
Thanks! What does the CI do exactly?

**Comment by SergioGasquez** [comment]
> Thanks! What does the CI do exactly?
- `cargo build`: Build the project
- `cargo test`: Will run the test (there are not test, if you do not plan to add tests we can remove it)
- `cargo fmt`: Will check the formating and fail if there is something not properly formated
- `cargo clippy`: Clippy lint checks
- `cargo doc`: Build the docs, same as tests, if there will non, we can remove it.
- `cargo publish`: Will run the command as if you were publishing it to `crates.io` but will not publish it

**Comment by urish** [comment]
Thanks!

I'm not sure we need any tests, since this is just the API function / struct declaration, with no actual logic.

As for docs - they are generated from the source code, right? In that case, we'll probably take them from https://gist.github.com/urish/f9129d3d34ffd557eccf354907663051 at some point

**Comment by SergioGasquez** [comment]
> I'm not sure we need any tests, since this is just the API function / struct declaration, with no actual logic.

Feel free to remove the test step then by removing this two lines: https://github.com/wokwi/wokwi_chip_ll/blob/main/.github/workflows/ci.yaml#L26-L27

> As for docs - they are generated from the source code, right? In that case, we'll probably take them from https://gist.github.com/urish/f9129d3d34ffd557eccf354907663051 at some point

Yes, Its generated from the source code and it will list all the struts, fns, constants...

**Pull request merged**
